name: desktop_app
description: Yemek Tespit Admin Panel - Windows Desktop App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  
  # Window yÃ¶netimi
  window_manager: ^0.3.8
  
  # Database
  sqflite_common_ffi: ^2.3.0
  
  # Security
  crypto: ^3.0.3
  
  # HTTP
  http: ^1.2.0
  http_parser: ^4.0.2
  
  # File & Image
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  
  # Utilities
  path_provider: ^2.1.0
  path: ^1.8.3
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  
  # State Management
  provider: ^6.1.1
  
  # Session Management
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
