name: food_detection_flutter
description: "Canlı kamera ile yemek tespit uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Kamera
  camera: ^0.11.0+2
  
  # HTTP client
  http: ^1.2.0
  
  # Firebase
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  
  # Yardımcı
  path: ^1.9.0
  
  # İzin yönetimi
  permission_handler: ^11.3.1
  
  # Resim seçici
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
